name: 📅 Daily Astro Report

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔽 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🐍 Установка зависимостей
        run: |
          python3 -m pip install --upgrade pip
          pip install skyfield

      - name: 🔮 Генерация астрологического отчёта
        run: python3 main.py

      - name: 🕰️ Генерация архива истории
        run: python3 utils/history_index.py

      - name: 📤 Коммит и пуш изменений
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/history/
          git commit -m "📅 Ежедневный отчёт + обновление архива" || echo "Нет изменений"
          git push origin main
