name: Daily Astrological Report

on:
  schedule:
    - cron: '0 5 * * *'  # каждый день в 5:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          pip install skyfield
          wget https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430t.bsp

      - name: Генерация отчёта
        run: python3 main.py

      - name: Коммит и пуш отчёта
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/history/
          git commit -m "🚀 Daily report $(date +'%Y-%m-%d')" || echo "No changes"
          git push
