name: Build and Deploy Whitepaper PDFs

on:
  push:
    branches: [main]
    paths:
      - 'docs/Whitepaper_*.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex fonts-dejavu

    - name: Build EN PDF
      if: ${{ exists('docs/Whitepaper_EN.md') }}
      run: pandoc docs/Whitepaper_EN.md -o docs/Whitepaper_EN.pdf --pdf-engine=xelatex -V mainfont="DejaVu Serif"

    - name: Build RU PDF
      if: ${{ exists('docs/Whitepaper_RU.md') }}
      run: pandoc docs/Whitepaper_RU.md -o docs/Whitepaper_RU.pdf --pdf-engine=xelatex -V mainfont="DejaVu Serif"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        keep_files: true
        destination_dir: docs
