name: Build Whitepapers

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/Whitepaper_EN.md'
      - 'docs/Whitepaper_RU.md'

jobs:
  build-pdfs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex fonts-dejavu

    - name: Build PDF from EN Markdown
      if: exists('docs/Whitepaper_EN.md')
      run: |
        pandoc docs/Whitepaper_EN.md -o docs/Whitepaper_EN.pdf --pdf-engine=xelatex -V mainfont="DejaVu Serif"

    - name: Build PDF from RU Markdown
      if: exists('docs/Whitepaper_RU.md')
      run: |
        pandoc docs/Whitepaper_RU.md -o docs/Whitepaper_RU.pdf --pdf-engine=xelatex -V mainfont="DejaVu Serif"

    - name: Push PDFs
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-generate Whitepaper PDFs"
        file_pattern: docs/*.pdf
