name: Convert Whitepaper to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'docs/Whitepaper_EN.md'
      - 'docs/Whitepaper_RU.md'
      - '.github/workflows/whitepaper-pdf.yml'
      - 'pandoc.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex fonts-dejavu

      - name: Build EN PDF
        run: |
          pandoc docs/Whitepaper_EN.md -o docs/Whitepaper_EN.pdf --defaults=pandoc.yaml

      - name: Build RU PDF
        run: |
          pandoc docs/Whitepaper_RU.md -o docs/Whitepaper_RU.pdf --defaults=pandoc.yaml

    - name: Commit & Push PDFs back
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add docs/*.pdf
        git commit -m "Auto-generate Whitepaper PDFs" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
        git push origin main
