name: Convert Whitepaper to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'docs/Whitepaper*.md'
      - '.github/workflows/whitepaper-pdf.yml'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc and TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert English Whitepaper to PDF
        run: pandoc docs/Whitepaper_EN.md -o docs/Whitepaper_EN.pdf

      - name: Convert Russian Whitepaper to PDF
        run: pandoc docs/Whitepaper_RU.md -o docs/Whitepaper_RU.pdf

      - name: Commit PDF files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
