name: Build Whitepaper PDFs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/Whitepaper_EN.md'
      - 'docs/Whitepaper_RU.md'

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build English Whitepaper
        run: pandoc docs/Whitepaper_EN.md -o docs/Whitepaper_EN.pdf

      - name: Build Russian Whitepaper
        run: pandoc docs/Whitepaper_RU.md -o docs/Whitepaper_RU.pdf

      - name: Commit PDFs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/Whitepaper_EN.pdf docs/Whitepaper_RU.pdf
          git commit -m "Auto-update Whitepapers (EN & RU) from .md" || echo "No changes to commit"
          git push
