name: Convert Whitepaper to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'docs/Whitepaper*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pandoc
        run: sudo apt-get install pandoc -y

      - name: Convert EN Whitepaper to PDF
        run: pandoc docs/Whitepaper_EN.md -o docs/Whitepaper_EN.pdf

      - name: Convert RU Whitepaper to PDF
        run: pandoc docs/Whitepaper_RU.md -o docs/Whitepaper_RU.pdf

      - name: Commit PDF
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add docs/*.pdf
          git commit -m 'Auto-generate Whitepaper PDFs'
          git push
