name: Convert Whitepaper to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'docs/Whitepaper_EN.md'
      - 'docs/Whitepaper_RU.md'
      - '.github/workflows/whitepaper-pdf.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Pandoc and XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex fonts-dejavu

      - name: Convert EN Whitepaper to PDF
        run: |
          pandoc docs/Whitepaper_EN.md -o docs/Whitepaper_EN.pdf --pdf-engine=xelatex

      - name: Convert RU Whitepaper to PDF
        run: |
          pandoc docs/Whitepaper_RU.md -o docs/Whitepaper_RU.pdf --pdf-engine=xelatex

      - name: Commit PDFs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/*.pdf
          git commit -m "Auto-generate Whitepaper PDFs"
          git push
